### ISSUE TITLE
Remove merge notations

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/Settings#1]
This should not be present, and may cause errors:
```
<<<<<<< HEAD
force ace_cookoff_ammoCookoffDuration = 0.3;
=======
force ace_cookoff_ammoCookoffDuration = 0.6;
>>>>>>> master
```

Above is only an example, there are multiple instances. It would probably be easiest to simply export a clean config.

@hazardouschurch

**Comment by hazardouschurch** [comment]
This is not live its me learning gitkracken will remove
